version: '3'
services:
  go:
    build: .
    command: ./start.sh
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=debug # debug | release
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    networks:
      - innernet

networks:
  innernet:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.68.7.128/28
